### Examples

In [1]:
import torch

In [3]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
#matrix
matrix = torch.tensor([[7, 8],
                     [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
#tensor
tensor = torch.tensor([[1, 2, 3],
                      [3, 6, 9], 
                      [2, 4, 5]])
tensor

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [12]:
tensor.ndim

2

# Lab Exercises

## Q1
Reshaping, viewing, stacking, squeezing and unsqueezing

In [16]:
t = torch.tensor([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]
])

In [22]:
t

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])

In [18]:
t.reshape([2, 8])

tensor([[1, 1, 1, 1, 2, 2, 2, 2],
        [3, 3, 3, 3, 4, 4, 4, 4]])

In [38]:
x = torch.tensor([1.,3.,6.,10.]) 
y = torch.tensor([2.,7.,9.,13.]) 
stacked = torch.stack((x, y))
print(x)
print(y)
print("stacked\n", stacked)

tensor([ 1.,  3.,  6., 10.])
tensor([ 2.,  7.,  9., 13.])
stacked
 tensor([[ 1.,  3.,  6., 10.],
        [ 2.,  7.,  9., 13.]])


In [36]:
s = t.reshape([1, 16])
squeezed = s.squeeze()
unsqueezed = squeezed.unsqueeze(dim=0)
print(s)
print("squeezed", squeezed)
print("unsqueezed", unsqueezed)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])
squeezed tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])
unsqueezed tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])


## Q2
torch.permute()

In [49]:
a = torch.tensor([[5, 6, 7]])
b = a.permute(1, 0)

print(a.shape)
print(b.shape)
print(b)

torch.Size([1, 3])
torch.Size([3, 1])
tensor([[5],
        [6],
        [7]])


## Q3
indexing in tensor

In [53]:
a = torch.tensor([[1, 2, 3],
                 [4, 5, 6]])
a[1]

tensor([4, 5, 6])

## Q4
numpy and tensors

In [54]:
import numpy as np

In [58]:
arr = np.array([[1, 2], [3, 4]])

t = torch.tensor(arr)
print(t)

a = t.numpy()
print(a)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


## Q5
random tensor 

In [60]:
t = torch.rand(7, 7)
t

tensor([[0.2977, 0.8290, 0.8176, 0.3719, 0.4697, 0.4676, 0.4562],
        [0.6065, 0.0112, 0.3375, 0.6600, 0.0913, 0.1518, 0.4250],
        [0.9787, 0.1673, 0.4076, 0.4896, 0.3007, 0.5319, 0.9900],
        [0.8114, 0.0118, 0.4341, 0.6175, 0.9526, 0.1924, 0.7718],
        [0.0709, 0.0941, 0.8192, 0.1068, 0.3738, 0.1545, 0.2061],
        [0.9250, 0.1661, 0.6106, 0.7411, 0.5783, 0.2993, 0.6325],
        [0.9404, 0.1152, 0.6112, 0.4994, 0.5913, 0.4231, 0.1299]])

## Q6
tensor multiplication

In [69]:
a = torch.rand(1, 7)
b = torch.transpose(a, 0, 1)
c = torch.matmul(a, b)
print(c)

tensor([[2.7007]])


## Q7
tensor on GPU

In [72]:
a = torch.rand(2, 3).cuda()
b = torch.rand(2, 3).cuda()

print(a)
print(b)

tensor([[0.2904, 0.0405, 0.6589],
        [0.9622, 0.6015, 0.9529]], device='cuda:0')
tensor([[0.3873, 0.0206, 0.6762],
        [0.4905, 0.7650, 0.0666]], device='cuda:0')


## Q8
matmul

In [75]:
b = b.reshape([3, 2])
c = torch.matmul(a, b)

print(c)

tensor([[0.6439, 0.0697],
        [1.5083, 0.3783]], device='cuda:0')


## Q9
max no of values of Q7

In [78]:
maxi = a.max()
mini = a.min()

print("max", maxi)
print("min", mini)

max tensor(0.9622, device='cuda:0')
min tensor(0.0405, device='cuda:0')


## Q10
indices of max and min values

In [82]:
maxi = a.argmax()
mini = a.argmin()

print("max", maxi)
print("min", mini)

max tensor(3, device='cuda:0')
min tensor(1, device='cuda:0')
