In [1]:
import numpy as np

# Q1
Convert a 1-D array into a 2-D array with 3 rows.

In [2]:
ary1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
ary1.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Q2
Replace all odd numbers in the given array with -1

In [3]:
ary2=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in range(len(ary2)):
    if ary2[i]%2==1:
        ary2[i]=-1
ary2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Q3
Find the positions of:

elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y.

In [4]:
x=np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y=np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

a1=np.array([])
a2=np.array([])
for i in range(len(x)):
    if x[i]>y[i]:
        a1=np.append(a1, [i])
    if x[i]==y[i]:
        a2=np.append(a2, [i])
print(a1, "and", a2)


[1. 2. 4. 5. 6. 7. 8. 9.] and [0.]


# Q4
Extract the first four columns of this 2-D array.

In [5]:
ary4=np.arange(100).reshape(5, -1)
ary4[::, :4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])