In [3]:
import numpy as np

# Q1
Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)

In [8]:
x=np.random.randint(30, 41, size=(10))
x

array([40, 39, 35, 32, 30, 36, 31, 40, 33, 35])

# Q2
Consider the following matrices :
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and   B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))
Write a python program to perform the following using Numeric Python (numpy).



i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.

In [9]:
a=[[1, 2, 3], [4, 5, 6], [7, 8, 10]]
b=[[7, 8, 10], [4, 5, 6], [1, 2, 3]]

In [13]:
c=np.add(a, b)
c

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [16]:
e=np.subtract(a, b)
e

array([[-6, -6, -7],
       [ 0,  0,  0],
       [ 6,  6,  7]])

ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C

In [26]:
sumA=np.sum(a)
sumB=np.sum(b, axis=0)
sumC=np.sum(c, axis=1)
print(sumA)
print(sumB)
print(sumC)

46
[12 15 19]
[31 30 31]


iii) Product of two matrices A and B, and print the resultant matrix D

In [23]:
f=np.dot(a, b)
f

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

iv) Sort the elements of resultant matrix C and print the resultant Matrix E.

In [24]:
e=np.sort(c)
e

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

v) Transpose the Matrix E and print the result

In [30]:
g=np.transpose(e)
g

array([[ 8,  8,  8],
       [10, 10, 10],
       [13, 12, 13]])